-- Up
CREATE TABLE IF NOT EXISTS Person (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  email TEXT,
  password TEXT
);

CREATE TABLE IF NOT EXISTS Vehicle (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  brand TEXT,
  model TEXT,
  ownerId INTEGER REFERENCES Person(id)
);



-- Down

DROP TABLE Person;
DROP TABLE Vehicle;
